# -*- coding: utf-8 -*-
"""
Builds data/fda_decisions_master.csv from a Python list of tuples.
Using csv.writer avoids manual escaping errors that corrupted earlier attempts.
Every row's source URLs were manually verified against FDA.gov, company press
releases (via SEC/GlobeNewswire/BusinessWire), and third-party pharma news
outlets during agent research (Sept 2026).
"""
import csv

HEADER = ["decision_id","company_name","ticker","exchange","drug_brand","drug_generic",
          "decision_type","decision_date","indication","review_pathway",
          "source_url_1","source_url_2","verification_status","notes"]

ROWS = [
("D001","Ligand Pharmaceuticals / Pelthos Therapeutics","LGND","NASDAQ","Zelsuvmi","berdazimer",
 "Approval","2024-01-05","Molluscum contagiosum","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217424s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified","First novel drug approved for molluscum contagiosum; asset later spun into Pelthos Therapeutics (PTHS)"),

("D002","Allecra Therapeutics (private) / commercial partner ADVANZ PHARMA (private)","NO_TICKER","N/A","Exblifep","cefepime and enmetazobactam",
 "Approval","2024-02-22","Complicated urinary tract infections","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/216165s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - no public ticker","Allecra Therapeutics and Advanz Pharma are both privately held; no listed equity to track"),

("D003","Sun Pharmaceutical Industries","SUNPHARMA.NS","NSE/BSE India; no US ADR","Letybo","letibotulinumtoxinA-wlbg",
 "Approval","2024-02-29","Glabellar lines","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761225s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - foreign listing only","Listed on Indian exchanges (NSE:SUNPHARMA / BSE:524715); no U.S. ticker"),

("D004","BeOne Medicines (formerly BeiGene)","ONC","NASDAQ","Tevimbra","tislelizumab-jsgr",
 "Approval","2024-03-13","Esophageal squamous cell carcinoma","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761232Orig1s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified","Company renamed from BeiGene to BeOne Medicines in 2025; ticker changed from BGNE to ONC"),

("D005","Madrigal Pharmaceuticals","MDGL","NASDAQ","Rezdiffra","resmetirom",
 "Approval (Accelerated)","2024-03-14","Noncirrhotic MASH with moderate-to-advanced liver fibrosis","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217785s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-first-treatment-patients-liver-scarring-due-fatty-liver-disease",
 "Verified","First FDA-approved MASH treatment"),

("D006","Idorsia Pharmaceuticals","IDIA.SW","SIX Swiss Exchange; no US ticker","Tryvio","aprocitentan",
 "Approval","2024-03-19","Hypertension (add-on)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217686s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - foreign listing only","Swiss-listed; no U.S.-listed ADR identified"),

("D007","Italfarmaco S.p.A. (parent, private) / ITF Therapeutics (US arm, private)","NO_TICKER","N/A","Duvyzat","givinostat",
 "Approval","2024-03-21","Duchenne muscular dystrophy (6 years and older)","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217865Orig1s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-nonsteroidal-treatment-duchenne-muscular-dystrophy",
 "Verified - no public ticker","Italfarmaco is a privately held Italian company"),

("D008","Merck & Co.","MRK","NYSE","Winrevair","sotatercept-csrk",
 "Approval","2024-03-26","Pulmonary arterial hypertension","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761363s000lbl.pdf",
 "https://www.ajmc.com/view/fda-approves-sotatercept-first-in-class-treatment-for-adults-with-pah",
 "Verified","Asset acquired via Merck's 2021 buyout of Acceleron Pharma"),

("D009","CSL Limited","CSL.AX","ASX Australia; no US ADR primary","Voydeya","danicopan",
 "Approval","2024-03-29","Extravascular hemolysis in PNH (add-on)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218037s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - foreign listing only","CSL Limited trades on ASX; thinly traded US OTC ADR CSLLY exists"),

("D010","Akebia Therapeutics","AKBA","NASDAQ","Vafseo","vadadustat",
 "Approval","2024-03-27","Anemia due to chronic kidney disease (dialysis patients)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/215192s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D011","Basilea Pharmaceutica (developer) / Innoviva (US rights holder)","INVA","NASDAQ","Zevtera","ceftobiprole medocaril sodium",
 "Approval","2024-04-03","MRSA bacteremia; ABSSSI; CABP","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218275s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-new-antibiotic-three-different-uses",
 "Verified","Basilea (SIX:BSLN) is Swiss-listed; Innoviva (NASDAQ:INVA) holds exclusive US rights since Dec 2024"),

("D012","Lumicell Inc. (private)","NO_TICKER","N/A","Lumisight","pegulicianine",
 "Approval","2024-04-17","Intraoperative breast cancer tissue detection","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/214511s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - no public ticker","Sponsor Lumicell Inc. is privately held"),

("D013","ImmunityBio","IBRX","NASDAQ","Anktiva","nogapendekin alfa inbakicept-pmln",
 "Approval","2024-04-22","BCG-unresponsive non-muscle invasive bladder cancer","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761336s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D014","Day One Biopharmaceuticals","DAWN","NASDAQ","Ojemda","tovorafenib",
 "Approval (Accelerated)","2024-04-23","Relapsed/refractory pediatric low-grade glioma","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218033s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D015","X4 Pharmaceuticals","XFOR","NASDAQ","Xolremdi","mavorixafor",
 "Approval","2024-04-26","WHIM syndrome","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218709s000lbl.pdf",
 "https://www.globenewswire.com/news-release/2024/04/29/2871050/0/en/X4-Pharmaceuticals-Announces-FDA-Approval-of-XOLREMDI-mavorixafor-Capsules-First-Drug-Indicated-in-Patients-with-WHIM-Syndrome.html",
 "Verified",""),

("D016","Amgen","AMGN","NASDAQ","Imdelltra","tarlatamab-dlle",
 "Approval (Accelerated)","2024-05-16","Extensive-stage small cell lung cancer","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D017","Geron Corporation","GERN","NASDAQ","Rytelo","imetelstat",
 "Approval","2024-06-06","Low-to-intermediate-1 risk myelodysplastic syndromes","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217779s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D018","Ipsen S.A.","IPN.PA","Euronext Paris; no US ticker","Iqirvo","elafibranor",
 "Approval (Accelerated)","2024-06-10","Primary biliary cholangitis (add-on)","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218860s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - foreign listing only","Ipsen S.A. trades on Euronext Paris; no primary US listing"),

("D019","Botanix Pharmaceuticals","BOT.AX","ASX Australia; US OTC as BTXXY","Sofdra","sofpironium",
 "Approval","2024-06-20","Primary axillary hyperhidrosis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217347s000lbl.pdf",
 "https://biotechdispatch.com.au/news/fda-approves-botanixs-sofdra-the-first-new-drug-for-primary-axillary-hyperhidrosis",
 "Verified - foreign listing primary","Primary listing ASX:BOT; thinly-traded US OTC ADR BTXXY exists"),

("D020","Verona Pharma plc","VRNA","NASDAQ","Ohtuvayre","ensifentrine",
 "Approval","2024-06-26","Chronic obstructive pulmonary disease","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217389s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified","Chiesi Farmaceutici is a partner in certain territories, not the NDA holder"),

("D021","Roche Holding AG (Genentech)","RHHBY","OTC ADR; primary SIX:ROG","Piasky","crovalimab-akkz",
 "Approval","2024-06-20","Paroxysmal nocturnal hemoglobinuria","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761388s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D022","Eli Lilly and Company","LLY","NYSE","Kisunla","donanemab-azbt",
 "Approval","2024-07-02","Alzheimer's disease","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761248s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D023","Sun Pharmaceutical Industries","SUNPHARMA.NS","NSE/BSE India; no US ADR","Leqselvi","deuruxolitinib",
 "Approval","2024-07-25","Severe alopecia areata","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217900Orig1s000correctedlbl.pdf",
 "https://synapse.patsnap.com/article/sun-pharmas-leqselvi-gets-fda-approval-for-severe-alopecia",
 "Verified - foreign listing only","Acquired via Concert Pharmaceuticals buyout ($576M, Jan 2023)"),

("D024","Bristol Myers Squibb","BMY","NYSE","Cobenfy","xanomeline and trospium chloride",
 "Approval","2024-09-26","Schizophrenia","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/216158s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-drug-new-mechanism-action-treatment-schizophrenia",
 "Verified","Acquired via Karuna Therapeutics buyout ($14B, 2024)"),

("D025","IntraBio Inc. (private)","NO_TICKER","N/A","Aqneursa","levacetylleucine",
 "Approval","2024-09-24","Niemann-Pick disease type C","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/219132s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-new-drug-treat-niemann-pick-disease-type-c",
 "Verified - no public ticker","IntraBio Inc. is privately held"),

("D026","Zevra Therapeutics","ZVRA","NASDAQ","Miplyffa","arimoclomol",
 "Approval","2024-09-20","Niemann-Pick disease type C (with miglustat)","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/214927s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-first-treatment-niemann-pick-disease-type-c",
 "Verified",""),

("D027","Eli Lilly and Company","LLY","NYSE","Ebglyss","lebrikizumab-lbkz",
 "Approval","2024-09-13","Moderate-to-severe atopic dermatitis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761306Orig1s000correctedlbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D028","Johnson & Johnson","JNJ","NYSE","Lazcluze","lazertinib",
 "Approval","2024-08-19","Non-small cell lung cancer (with amivantamab)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/219008s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D029","Incyte Corporation","INCY","NASDAQ","Niktimvo","axatilimab-csfr",
 "Approval","2024-08-14","Chronic graft-versus-host disease","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761411s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified","Co-developed with Syndax Pharmaceuticals (NASDAQ:SNDX)"),

("D030","Gilead Sciences","GILD","NASDAQ","Livdelzi","seladelpar",
 "Approval (Accelerated)","2024-08-14","Primary biliary cholangitis","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/217899s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified","Gilead acquired CymaBay Therapeutics in 2024"),

("D031","Galderma Group AG","GALD.SW","SIX Swiss Exchange; no US ticker","Nemluvio","nemolizumab-ilto",
 "Approval","2024-08-12","Prurigo nodularis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761390s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - foreign listing only","Galderma listed on SIX Swiss Exchange since 2024 IPO"),

("D032","Ascendis Pharma","ASND","NASDAQ","Yorvipath","palopegteriparatide",
 "Approval","2024-08-09","Hypoparathyroidism","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/216490s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D033","Servier Pharmaceuticals (private)","NO_TICKER","N/A","Voranigo","vorasidenib",
 "Approval","2024-08-06","Grade 2 astrocytoma/oligodendroglioma","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218784s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified - no public ticker","Servier is a privately held French pharmaceutical group"),

("D034","Zymeworks Inc.","ZYME","NASDAQ","Ziihera","zanidatamab-hrii",
 "Approval (Accelerated)","2024-11-20","HER2-positive biliary tract cancer","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761416s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified","Jazz Pharmaceuticals holds commercial rights"),

("D035","Syndax Pharmaceuticals","SNDX","NASDAQ","Revuforj","revumenib",
 "Approval","2024-11-15","Relapsed/refractory KMT2A-rearranged acute leukemia","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218944s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D036","Iterum Therapeutics","ITRM","NASDAQ","Orlynvah","sulopenem etzadroxil and probenecid",
 "Approval","2024-10-25","Uncomplicated urinary tract infections","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/213972s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D037","Pfizer","PFE","NYSE","Hympavzi","marstacimab-hncq",
 "Approval","2024-10-11","Hemophilia A/B (routine prophylaxis)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761369s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-new-treatment-hemophilia-or-b",
 "Verified",""),

("D038","Roche Holding AG (Genentech)","RHHBY","OTC ADR; primary SIX:ROG","Itovebi","inavolisib",
 "Approval","2024-10-10","PIK3CA-mutated advanced/metastatic breast cancer","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/219249s001lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D039","GE HealthCare Technologies","GEHC","NASDAQ","Flyrcado","flurpiridaz F 18",
 "Approval","2024-09-27","Myocardial perfusion imaging","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/215168s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D040","Ionis Pharmaceuticals","IONS","NASDAQ","Tryngolza","olezarsen",
 "Approval","2024-12-19","Familial chylomicronemia syndrome","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218614s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D041","Vertex Pharmaceuticals","VRTX","NASDAQ","Alyftrek","vanzacaftor, tezacaftor, and deutivacaftor",
 "Approval","2024-12-20","Cystic fibrosis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/218730s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D042","Novo Nordisk","NVO","NYSE","Alhemo","concizumab-mtci",
 "Approval","2024-12-20","Hemophilia A/B (routine prophylaxis)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761315s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2024",
 "Verified",""),

("D043","AstraZeneca / Daiichi Sankyo","AZN","NASDAQ","Datroway","datopotamab deruxtecan-dlnk",
 "Approval","2025-01-17","HR-positive HER2-negative metastatic breast cancer","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761394s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified","Co-developed by AstraZeneca and Daiichi Sankyo (DSNKY OTC)"),

("D044","medac GmbH (private)","NO_TICKER","N/A","Grafapex","treosulfan",
 "Approval","2025-01-21","Conditioning regimen for HSCT (AML/MDS)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/214759s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - no public ticker","medac GmbH is a privately held German company; US distribution via Medexus Pharmaceuticals"),

("D045","Vertex Pharmaceuticals","VRTX","NASDAQ","Journavx","suzetrigine",
 "Approval","2025-01-30","Moderate-to-severe acute pain","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219209s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-novel-non-opioid-treatment-moderate-severe-acute-pain",
 "Verified",""),

("D046","SpringWorks Therapeutics","SWTX","NASDAQ","Gomekli","mirdametinib",
 "Approval","2025-02-11","Neurofibromatosis type 1 with plexiform neurofibromas","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219379Orig1s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D047","Deciphera Pharmaceuticals (acquired by ONO Pharmaceutical, 2025)","NO_TICKER","formerly NASDAQ:DCPH, delisted","Romvimza","vimseltinib",
 "Approval","2025-02-14","Tenosynovial giant cell tumor","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219304s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - now private subsidiary","Deciphera acquired by ONO Pharmaceutical (TSE:4528) in 2025; DCPH delisted"),

("D048","Sanofi","SNY","NASDAQ","Qfitlia","fitusiran",
 "Approval","2025-03-28","Hemophilia A/B (with/without inhibitors)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219019s000lbl.pdf",
 "https://www.fda.gov/news-events/press-announcements/fda-approves-novel-treatment-hemophilia-or-b-or-without-factor-inhibitors",
 "Verified",""),

("D049","GSK plc","GSK","NYSE","Blujepa","gepotidacin",
 "Approval","2025-03-25","Uncomplicated urinary tract infections","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/218230s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D050","Novartis AG","NVS","NYSE","Vanrafia","atrasentan",
 "Approval (Accelerated)","2025-04-02","IgA nephropathy (proteinuria reduction)","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219208s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D051","Akeso Inc.","9926.HK","HKEX Hong Kong; no US ticker","penpulimab-kcqx","penpulimab-kcqx",
 "Approval","2025-04-23","Nasopharyngeal carcinoma","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761258Orig1s000correctedlbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - foreign listing only","Akeso's first internally-developed biologic approved by FDA; HK-listed only"),

("D052","Johnson & Johnson","JNJ","NYSE","Imaavy","nipocalimab-aahu",
 "Approval","2025-04-29","Generalized myasthenia gravis","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761430s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D053","AbbVie","ABBV","NYSE","Emrelis","telisotuzumab vedotin-tllv",
 "Approval (Accelerated)","2025-05-14","c-Met overexpressing non-squamous NSCLC","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761384s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D054","Verastem Oncology","VSTM","NASDAQ","Avmapki Fakzynja Co-Pack","avutometinib and defactinib",
 "Approval (Accelerated)","2025-05-08","KRAS-mutated recurrent low-grade serous ovarian cancer","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219616s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D055","Alcon Inc.","ALC","NYSE","Tryptyr","acoltremon",
 "Approval","2025-05-28","Dry eye disease","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/217370s000lbl.pdf",
 "https://www.hcplive.com/view/fda-approves-acoltremon-ophthalmic-solution-tryptyr-for-dry-eye-disease",
 "Verified",""),

("D056","Nuvation Bio","NUVB","NYSE","Ibtrozi","taletrectinib",
 "Approval","2025-06-11","ROS1-positive non-small cell lung cancer","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219713s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D057","Merck & Co.","MRK","NYSE","Enflonsia","clesrovimab-cfor",
 "Approval","2025-06-09","RSV prevention in neonates/infants","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761432s000lbledt.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D058","Innoviva Specialty Therapeutics (Innoviva Inc.)","INVA","NASDAQ","Nuzolvence","zoliflodacin",
 "Approval","2025-12-12","Uncomplicated urogenital gonorrhea","Standard",
 "https://investor.inva.com/news-releases/news-release-details/us-fda-approves-nuzolvencer-zoliflodacin-first-class-single-dose",
 "https://gardp.org/portfolio/zoliflodacin/",
 "Verified","Developed with nonprofit GARDP; first new gonorrhea treatment in ~20 years"),

("D059","Dizal Pharmaceuticals (private at time of approval)","NO_TICKER","N/A","Zegfrovy","sunvozertinib",
 "Approval (Accelerated)","2025-07-02","EGFR exon20ins NSCLC","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219839s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - private at approval","Dizal was privately held at the time of FDA approval"),

("D060","Regeneron Pharmaceuticals","REGN","NASDAQ","Lynozyfic","linvoseltamab-gcpt",
 "Approval (Accelerated)","2025-07-02","Relapsed/refractory multiple myeloma","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761400s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D061","CSL Limited","CSL.AX","ASX Australia; no US ADR primary","Andembry","garadacimab-gxii",
 "Approval","2025-06-16","Hereditary angioedema prophylaxis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761367s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - foreign listing only",""),

("D062","Boehringer Ingelheim (private)","NO_TICKER","N/A","Jascayd","nerandomilast",
 "Approval","2025-10-07","Idiopathic pulmonary fibrosis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/218764s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - no public ticker","Boehringer Ingelheim is a privately held German company"),

("D063","Novartis AG","NVS","NYSE","Rhapsido","remibrutinib",
 "Approval","2025-09-30","Chronic spontaneous urticaria","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/218436s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D064","Crinetics Pharmaceuticals","CRNX","NASDAQ","Palsonify","paltusotine",
 "Approval","2025-09-25","Acromegaly","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219070s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D065","Eli Lilly and Company","LLY","NYSE","Inluriyo","imlunestrant",
 "Approval","2025-09-25","ESR1-mutated advanced/metastatic breast cancer","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/218881s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D066","Stealth BioTherapeutics","MITO","NASDAQ","Forzinity","elamipretide",
 "Approval","2025-09-19","Barth syndrome (muscle strength)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/215244s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D067","Merck & Co.","MRK","NYSE","Keytruda Qlex","pembrolizumab and berahyaluronidase alfa-pmph",
 "Approval","2025-09-19","Solid tumors (subcutaneous pembrolizumab formulation)","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761467s000lblOrig2.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D068","Sanofi","SNY","NASDAQ","Wayrilz","rilzabrutinib",
 "Approval","2025-08-29","Persistent/chronic immune thrombocytopenia","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219685s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D069","Ionis Pharmaceuticals","IONS","NASDAQ","Dawnzera","donidalorsen",
 "Approval","2025-08-21","Hereditary angioedema prophylaxis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219407s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D070","Insmed Incorporated","INSM","NASDAQ","Brinsupri","brensocatib",
 "Approval","2025-08-12","Non-cystic fibrosis bronchiectasis","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/217673s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D071","Boehringer Ingelheim (private)","NO_TICKER","N/A","Hernexeos","zongertinib",
 "Approval","2025-08-08","HER2-mutated NSCLC","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219042s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - no public ticker",""),

("D072","Chimerix Inc.","CMRX","NASDAQ","Modeyso","dordaviprone",
 "Approval (Accelerated)","2025-08-06","H3 K27M-mutant diffuse midline glioma","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219876s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D073","LENZ Therapeutics","LENZ","NASDAQ","Vizz","aceclidine",
 "Approval","2025-07-31","Presbyopia","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/218585s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D074","PTC Therapeutics","PTCT","NASDAQ","Sephience","sepiapterin",
 "Approval","2025-07-28","Sepiapterin-responsive phenylketonuria","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219666s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D075","LEO Pharma (private, foundation-owned)","NO_TICKER","N/A","Anzupgo","delgocitinib",
 "Approval","2025-07-23","Chronic hand eczema","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219155s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - no public ticker","LEO Pharma is owned by the LEO Foundation"),

("D076","KalVista Pharmaceuticals","KALV","NASDAQ","Ekterly","sebetralstat",
 "Approval","2025-07-03","Acute hereditary angioedema attacks","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219301s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D077","UCB S.A.","UCB.BR","Euronext Brussels; no US ticker","Kygevvi","doxecitine and doxribtimine",
 "Approval","2025-11-03","Thymidine kinase 2 deficiency","Priority",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "https://www.neurologylive.com/view/fda-approves-doxecitine-doxribtimine-combination-therapy-first-treatment-thymidine-kinase-2-deficiency",
 "Verified - foreign listing only","UCB trades on Euronext Brussels; no US ADR"),

("D078","Kura Oncology","KURA","NASDAQ","Komzifti","ziftomenib",
 "Approval","2025-11-13","Relapsed/refractory NPM1-mutated AML","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/220305s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified","Co-developed with Kyowa Kirin"),

("D079","Arrowhead Pharmaceuticals","ARWR","NASDAQ","Redemplo","plozasiran",
 "Approval","2025-11-18","Familial chylomicronemia syndrome","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219947s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D080","Bayer AG","BAYRY","OTC ADR; primary XETRA:BAYN","Hyrnuo","sevabertinib",
 "Approval (Accelerated)","2025-11-19","HER2-mutated non-squamous NSCLC","Priority/Accelerated",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219972s000lblCorrected.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D081","LIB Therapeutics (private)","NO_TICKER","N/A","Lerochol","lerodalcibep-liga",
 "Approval","2025-12-12","Hypercholesterolemia (incl. HeFH)","Standard",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "https://www.drugs.com/pro/lerochol.html",
 "Verified - no public ticker","LIB Therapeutics is privately held"),

("D082","Otsuka Holdings (parent) / Visterra (private US subsidiary)","4578.T","TSE Japan (parent only)","Voyxact","sibeprenlimab-szsi",
 "Approval","2025-11-25","IgA nephropathy (proteinuria reduction)","Priority",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219434s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified - foreign parent listing only","Otsuka Holdings trades on Tokyo Stock Exchange (4578); Visterra subsidiary not separately listed"),

("D083","Milestone Pharmaceuticals","MIST","NASDAQ","Cardamyst","etripamil",
 "Approval","2025-12-12","Paroxysmal supraventricular tachycardia","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/218571s000lbl.pdf",
 "https://www.nasdaq.com/articles/fda-approves-milestone-pharma-cardamyst-first-self-administered-treatment-psvt",
 "Verified","First new PSVT treatment approved in over 30 years"),

("D084","GSK plc","GSK","NYSE","Exdensur","depemokimab-ulaa",
 "Approval","2025-12-16","Severe eosinophilic asthma (add-on)","Standard",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "https://www.fda.gov/drugs/drug-trials-snapshots/drug-trials-snapshots-exdensur",
 "Verified",""),

("D085","Cytokinetics Incorporated","CYTK","NASDAQ","Myqorzo","aficamten",
 "Approval","2025-12-19","Symptomatic obstructive hypertrophic cardiomyopathy","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219083s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D086","Omeros Corporation","OMER","NASDAQ","Yartemlea","narsoplimab-wuug",
 "Approval","2025-12-23","Hematopoietic stem cell transplant-associated TMA","Standard",
 "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761152Orig1s000lbl.pdf",
 "https://www.fda.gov/drugs/novel-drug-approvals-fda/novel-drug-approvals-2025",
 "Verified",""),

("D087","Fortress Biotech / Cyprium Therapeutics (majority-owned subsidiary)","FBIO","NASDAQ","Zycubo","copper histidinate",
 "Approval","2026-01-13","Menkes disease","Priority",
 "https://globalgenes.org/raredaily/fda-approves-sentynls-therapy-for-menkes-disease/",
 "https://www.sec.gov/Archives/edgar/data/1429260/000110465926003121/fbio-20260113xex99d1.htm",
 "Verified","PRV transferred from Sentynl (private, held NDA) to Fortress subsidiary Cyprium at approval"),

("D088","GSK plc (marketer) / Spero Therapeutics (originator)","SPRO","NASDAQ","Utebzi","tebipenem pivoxil",
 "Approval","2026-06-17","Complicated urinary tract infections","Standard",
 "https://www.healio.com/news/primary-care/20260617/fda-approves-oral-utebzi-for-complicated-utis",
 "https://us.gsk.com/en-us/media/press-releases/utebzi-tebipenem-pivoxil-approved-in-the-us-for-adults-with-complicated-urinary-tract-infections-cutis/",
 "Verified","GSK holds global license from Spero Therapeutics excluding select Asian territories"),

("D089","Denali Therapeutics","DNLI","NASDAQ","Avlayah","tividenofusp alfa-eknm",
 "Approval (Accelerated)","2026-03-24","Neurologic manifestations of Hunter syndrome (MPS II)","Priority/Accelerated",
 "https://practicalneurology.com/news/fda-approves-avlayah-for-neurologic-manifestations-of-hunter-syndrome/2486410/",
 "https://www.hhs.gov/press-room/wtas-fda-approves-drug-treat-neurologic-manifestations-hunter-syndrome.html",
 "Verified","First therapy addressing CNS complications of Hunter syndrome"),

("D090","Immedica Pharma AB (private, Sweden)","NO_TICKER","N/A","Loargys","pegzilarginase-nbln",
 "Approval (Accelerated)","2026-02-23","Arginase 1 deficiency","Priority/Accelerated",
 "https://www.onyxnewsroom.com/immedica-pharmas-loargys-adds-an-enzyme-replacement-entrant-for-ultra-rare-arg1-d-related-hyperargininemia/",
 "https://www.immedica.com/en/press/us-fda-has-granted-accelerated-approval-loargysr-pegzilarginase-nbln-treatment",
 "Verified - no public ticker","Aeglea BioTherapeutics (formerly NASDAQ:AGLE) acquired by Immedica Pharma in 2023; Aeglea delisted"),

("D091","BeOne Medicines (formerly BeiGene)","ONC","NASDAQ","Beqalzi","sonrotoclax",
 "Approval (Accelerated)","2026-05-13","Relapsed/refractory mantle cell lymphoma","Priority/Accelerated",
 "https://checkrare.com/accelerated-approval-granted-to-beqalzi-sonrotoclax-for-mantle-cell-lymphoma/",
 "https://www.curetoday.com/view/fda-approves-beqalzi-for-relapsed-mantle-cell-lymphoma",
 "Verified","First BCL2 inhibitor approved for relapsed/refractory MCL"),

("D092","Takeda Pharmaceutical Company","TAK","NYSE","Orzeyful","oveporexton",
 "Approval","2026-08-05","Narcolepsy type 1","Priority",
 "https://www.takeda.com/newsroom/newsreleases/2026/orzeyful-approved-narcolepsy/",
 "https://www.psychiatrictimes.com/view/fda-approves-oveporexton-for-narcolepsy-type-1-first-drug-to-treat-full-range-of-nt1-symptoms",
 "Verified","First orexin receptor agonist approved for NT1"),

("D093","Revolution Medicines","RVMD","NASDAQ","Rasonque","daraxonrasib",
 "Approval","2026-08-26","Metastatic pancreatic adenocarcinoma","Standard",
 "https://www.fda.gov/drugs/resources-information-approved-drugs/fda-approves-daraxonrasib-metastatic-pancreatic-adenocarcinoma",
 "https://www.globenewswire.com/news-release/2026/08/26/3351615/0/en/u-s-fda-approves-revolution-medicines-rasonque-daraxonrasib-the-first-broad-ras-targeted-medicine-in-metastatic-pancreatic-cancer.html",
 "Verified","First broad RAS(ON)-targeted medicine approved"),

("D094","Roivant Sciences / Priovant Therapeutics (subsidiary)","ROIV","NASDAQ","Lisraya","brepocitinib",
 "Approval","2026-08-27","Dermatomyositis (adults)","Priority",
 "https://allsci.com/news/approvals/lisraya-dermatomyositis-fda-approval-approves-as/",
 "https://www.healio.com/news/dermatology/20260828/fda-approves-lisraya-as-first-oral-drug-for-dermatomyositis",
 "Verified","First oral drug approved for dermatomyositis; molecule originally Pfizer's PF-06700841"),

("D095","Takeda Pharmaceutical Company (US rights) / Protagonist Therapeutics (originator)","PTGX","NASDAQ","Mimrylo","rusfertide",
 "Approval","2026-08-28","Erythrocytosis in polycythemia vera","Standard",
 "https://www.takeda.com/newsroom/newsreleases/2026/fda-approval-mimrylo/",
 "https://www.accessnewswire.com/newsroom/en/healthcare-and-pharmaceutical/protagonist-therapeutics-announces-u.s.-fda-approval-of-hepcidin-mime-1214342",
 "Verified","Takeda holds global commercial rights via partnership with Protagonist Therapeutics; supported by Phase 3 VERIFY trial"),

("D096","Aurobindo Pharma (parent, India-listed) / Acrotech Biopharma (private US subsidiary)","AUROPHARMA.NS","NSE/BSE India; no US ADR","Adquey","difamilast",
 "Approval","2026-02-13","Mild-to-moderate atopic dermatitis","Standard",
 "https://www.pharmaindiamagazine.com/acrotech-biopharma-inc-announces-fda-approval-of-adquey-ointment/",
 "https://scanx.trade/stock-market-news/stocks/aurobindo-pharma-s-subsidiary-acrotech-receives-fda-approval-for-adquey-ointment-for-atopic-dermatitis-treatment/32536601",
 "Verified - foreign listing only","Developed in collaboration with Otsuka Pharmaceutical"),

("D097","Vanda Pharmaceuticals","VNDA","NASDAQ","Bysanti","milsaperidone",
 "Approval","2026-02-20","Schizophrenia; bipolar I mania","Standard",
 "https://laafon.com/fda-novel-drug/bysanti-fda-approval-treatment-for-schizophrenia-bipolar-i/",
 "https://www.investing.com/news/company-news/fda-approves-vandas-bysanti-for-bipolar-disorder-schizophrenia-93CH-4517356",
 "Verified","Second Vanda approval within two months (after Nereus, Dec 2025)"),

("D098","Ascendis Pharma","ASND","NASDAQ","Yuviwel","navepegritide",
 "Approval (Accelerated)","2026-02-27","Achondroplasia (linear growth)","Priority/Accelerated",
 "https://www.contemporarypediatrics.com/view/fda-issues-historic-approval-for-navepegritide-in-achondroplasia",
 "https://finance.yahoo.com/news/ascendis-pharma-maps-2026-u-025442951.html",
 "Verified","Ascendis's third FDA-approved TransCon product"),

("D099","Haisco Pharmaceutical Group","002653.SZ","SZSE China; no US ticker","Cypsedo","cipepofol",
 "Approval","2026-05-31","General anesthesia induction (adults)","Standard",
 "https://chemxpert.com/all-news/haiscos-cipepofol-becomes-the-first-china-originated-innovative-intravenous-anesthetic-approved-by-the-us-fda",
 "https://filingreader.com/news-wire/shenzhen/2026-06-01/haisco-pharmaceutical-drug-cipepofol-wins-us-fda-approval",
 "Verified - foreign listing only","First China-originated innovative IV anesthetic approved by FDA"),

("D100","Otsuka Pharmaceutical (parent Otsuka Holdings)","4578.T","TSE Japan; no US ticker","Simtriyo","centanafadine",
 "Approval","2026-07-24","Attention-deficit hyperactivity disorder","Standard",
 "https://www.psychiatrictimes.com/view/fda-approves-centanafadine-for-adhd-in-children-adolescents-and-adults",
 "https://www.delveinsight.com/blog/simtriyo-approval-for-adhd",
 "Verified - foreign parent listing only","First-in-class NDSRI for ADHD; co-developed with Tris Pharma (private)"),
]

with open("data/fda_decisions_master.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(HEADER)
    w.writerows(ROWS)

print(f"Wrote {len(ROWS)} rows")
