#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""v28 (2026-09-21): FDA decisions BEFORE the project's earliest covered year.

The task
--------
Extend, add and analyse FDA decisions before the earliest year the project
covered when this session started. After v26/v27 that earliest year was
**1939** (``data/pre1965_fda_decisions.csv`` starts at 1939-02-09) with 1938
documented as a verified negative (``data/pre1938_determination.csv``).

So the honest question is not "what approvals happened in 1938" but:

  *is there anything at all before 1939 in any official record, and if not,
  what exactly proves it, and what governed drugs before the approval system
  existed?*

This builder answers that with four auditable tables. It invents no decisions.
Where the official record is silent, the silence is the published result, with
the evidence line that establishes it.

What this builder proves, from committed primary sources only
------------------------------------------------------------
1. **Application-number census below the boundary.** The unfiltered official
   Drugs@FDA application map (``Applications_all_types.txt``, 29,336 rows,
   SHA-manifested) contains **exactly two** applications numbered below
   NDA000552 - the application that carries the first recorded FDA drug
   approval action (1939-02-09): ``000004`` (NDA, PHARMICS) and ``000159``
   (NDA, LILLY). Every submission row for each is copied verbatim.
2. **1939-02-09 is the boundary.** In the official 1938-1964 Submissions
   window (1,215 rows) the earliest ``SubmissionStatusDate`` is
   ``1939-02-09 00:00:00`` on ApplNo 000552 (ORIG 1, AP, class 19), and there
   are **0 rows dated in 1938**.
3. **The openFDA payload block starts at 1939.** The committed payloads are
   ``decisions_1939.json`` .. ``decisions_1964.json`` - there is no 1938 file.
4. **The official Drugs@FDA Submissions table publishes approvals only.**
   Both committed windows are 100% ``AP`` (1,215/1,215 for 1939-1964 and
   10,753/10,753 for 1965-1979; submission types ORIG/SUPPL only). v27's site
   copy claimed the 1938-1964 register held "ORIG/AP plus RE, W, etc." and
   that "non-approval decisions (rejections/withdrawals) live" there. **That
   claim is not supported by the data and is corrected here.**
5. **The pre-1939 regulatory framework, year by year 1902-1938.** Statutes are
   quoted from the U.S. Statutes at Large via govinfo.gov and the FDA's own
   history pages. The decisive structural fact: the 1906 Food and Drugs Act
   (ch. 3915, 34 Stat. 768) contained **no pre-market approval requirement** -
   it prohibited adulterated/misbranded drugs in interstate commerce and put
   examinations in the Bureau of Chemistry, USDA. Federal pre-market
   *licensure* of a drug class existed earlier still, under the Biologics
   Control Act of 1902 (ch. 1378, 32 Stat. 728), where a virus/serum/toxin/
   antitoxin could not be sold unless made in an establishment holding an
   unrevoked license "issued by the Secretary of the Treasury". The general
   new-drug application was created by the 1938 FD&C Act (ch. 675,
   52 Stat. 1040), now codified at 21 U.S.C. 355(a).

Tables owned (rewritten deterministically on every run)
------------------------------------------------------
* ``data/pre1939_boundary_determination.csv``          (evidence lines)
* ``data/pre1939_application_census.csv``              (below-boundary apps)
* ``data/pre1939_regulatory_register_1902_1938.csv``   (37 year rows)
* ``data/pre1939_submission_status_census.csv``        (per-year status census)

Optional runner captures
------------------------
``fetch_jobs/drugsatfda_pre1939_census_v28.json`` (generated by
``scripts/gen_pre1939_census_job_v28.py``) captures the three things a
year-filtered window cannot: rows dated before 1939 anywhere in the 193,752-row
official table, rows with an unparseable status date (invisible to every year
filter), and the whole-table ``SubmissionStatus``/``SubmissionType`` census.
When ``data/raw/drugsatfda_pre1939_census_v28/manifest.json`` exists, the
builder re-hashes each capture against it and **aborts on any disagreement**
with the window-derived facts. Until it lands, the evidence rows say so
explicitly instead of overclaiming.

Fail-closed rules
-----------------
* SHA-256 of every committed input vs its runner manifest;
* ``Applications_all_types.txt`` must have exactly 29,336 applications;
* the below-boundary application set is *derived*, then compared with the
  captured census when present (mismatch aborts);
* 0 rows dated 1938, earliest date 1939-02-09 on ApplNo 000552, all statuses
  ``AP`` - any drift aborts;
* the v27 ``fda_1938_1964_full_submission_register.csv`` must reproduce the
  official extract row-for-row (key equality), else abort;
* no ticker, indication, corporate lineage, likelihood or probability column
  is written anywhere in any v28 table.
"""
from __future__ import annotations

import csv
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

RAW_1938_64 = DATA / "raw" / "drugsatfda_data_files_1938_1964"
RAW_2026_09 = DATA / "raw" / "drugsatfda_data_files_2026_09"
RAW_CENSUS = DATA / "raw" / "drugsatfda_pre1939_census_v28"
PAYLOAD_DIR = DATA / "raw" / "openfda_orig_decisions_1939_1964"

BOUNDARY_CSV = DATA / "pre1939_boundary_determination.csv"
CENSUS_CSV = DATA / "pre1939_application_census.csv"
REGISTER_CSV = DATA / "pre1939_regulatory_register_1902_1938.csv"
STATUS_CSV = DATA / "pre1939_submission_status_census.csv"

APPS_ALL = RAW_2026_09 / "Applications_all_types.txt"
SUBS_1938_64 = RAW_1938_64 / "Submissions_1938_1964.txt"
APPS_1938_64 = RAW_1938_64 / "Applications_1938_1964_window.txt"
SUBS_1965_79 = RAW_2026_09 / "Submissions_1965_1979.txt"

V27_REGISTER = DATA / "fda_1938_1964_full_submission_register.csv"
V27_1938_DET = DATA / "pre1938_determination.csv"
OFFICIAL_SERIES = DATA / "fda_official_year_series.csv"

V28 = "v28 (2026-09-21)"
EXPECTED_APPS_TOTAL = 29336
BOUNDARY_APPLNO = 552
EARLIEST_DATE = "1939-02-09 00:00:00"
EARLIEST_APPLNO = "000552"

DRUGSATFDA = ("https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm"
              "?event=overview.process&varApplNo={appl}")

# ---- verified primary sources -------------------------------------------------
# Every URL below was retrieved and read during the v28 session; the quoted
# text in `quotes` is copied from what was retrieved, not from memory.
SRC_1902 = "https://www.govinfo.gov/content/pkg/STATUTE-32/pdf/STATUTE-32-Pg728.pdf"
SRC_1906 = "https://www.govinfo.gov/content/pkg/STATUTE-34/pdf/STATUTE-34-Pg768.pdf"
SRC_1912 = "https://www.govinfo.gov/content/pkg/STATUTE-37/pdf/STATUTE-37-Pg416.pdf"
SRC_1938 = "https://www.govinfo.gov/content/pkg/STATUTE-52/pdf/STATUTE-52-Pg1040.pdf"
SRC_USC355 = ("https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-"
              "title21-section355&num=0&edition=prelim")
SRC_FDA_HISTORY = ("https://www.fda.gov/about-fda/fda-history-research-tools/"
                   "background-research-tools-fda-history")
SRC_FDA_SERIES = ("https://www.fda.gov/about-fda/histories-fda-regulated-products/"
                  "summary-nda-approvals-receipts-1938-present")
SRC_USDA_FSIS = "https://www.fsis.usda.gov/about-fsis/history"

QUOTE_1902 = ('"no person shall sell, barter, or exchange ... any virus, therapeutic '
              'serum, toxin, antitoxin, or analogous product applicable to the prevention '
              'and cure of diseases of man, unless (a) such virus, serum, toxin, antitoxin, '
              'or product has been propagated and prepared at an establishment holding an '
              'unsuspended and unrevoked license, issued by the Secretary of the Treasury"')
QUOTE_1906 = ('Sec. 4: "the examinations of specimens of foods and drugs shall be made in '
              'the Bureau of Chemistry of the Department of Agriculture". The Act creates '
              'no approval procedure: enforcement is by adulteration/misbranding prohibition, '
              'notice, certification to the district attorney, seizure and criminal penalty.')
QUOTE_1912 = ('adds a third paragraph to Sec. 8: "If its package or label shall bear or '
              'contain any statement, design, or device regarding the curative or therapeutic '
              'effect of such article ... which is false and fraudulent."')
QUOTE_1938 = ('"This Act may be cited as the Federal Food, Drug, and Cosmetic Act" (Sec. 1). '
              'The new-drug application requirement it created is now codified at 21 U.S.C. '
              '355(a): "No person shall introduce or deliver for introduction into interstate '
              'commerce any new drug, unless an approval of an application filed pursuant to '
              'subsection (b) or (j) is effective with respect to such drug."')
QUOTE_FDA_HISTORY = ('"In 1927 Congress authorized the formation of the Food, Drug, and '
                     'Insecticide Administration from the regulatory wing of the Bureau of '
                     'Chemistry; the name of the agency was shortened to the Food and Drug '
                     'Administration in 1930."')

BOUNDARY_HEADER = ["evidence_id", "category", "claim", "method", "observed_value",
                   "source_file", "source_sha256_prefix", "source_url",
                   "verification_status", "notes"]

CENSUS_HEADER = ["census_id", "appl_no", "application_number", "appl_type",
                 "sponsor_name_official_db", "appl_public_notes",
                 "in_official_applications_map", "n_submission_rows_committed_windows",
                 "submission_rows_verbatim", "earliest_recorded_action_date",
                 "latest_recorded_action_date", "decision_recorded_before_1939",
                 "first_product_brand_official_payload", "first_product_ingredients",
                 "first_product_form_route", "first_product_marketing_status",
                 "nme_comparable", "tracked_in_project_table", "project_table_row_id",
                 "drugsatfda_url", "source_file", "source_url",
                 "verification_status", "flags", "notes"]

REGISTER_HEADER = ["row_id", "year", "era", "agency_of_record",
                   "premarket_approval_regime", "statute_citation",
                   "statute_enacted_date", "statute_verbatim_quote",
                   "fda_drug_approval_decisions_recorded",
                   "recorded_decisions_basis", "official_fda_series_coverage",
                   "landmark_event", "determination", "source_url_1",
                   "source_url_2", "source_url_3", "verification_status", "notes"]

STATUS_HEADER = ["census_id", "source_window", "year", "total_rows",
                 "orig_ap_rows", "suppl_ap_rows", "other_type_rows",
                 "distinct_statuses", "non_ap_rows", "determination",
                 "source_file", "source_sha256_prefix", "source_url",
                 "verification_status", "notes"]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_tsv(path: Path) -> tuple[list[dict], list[str]]:
    with path.open(newline="", encoding="latin-1") as fh:
        rdr = csv.DictReader(fh, delimiter="\t")
        rows = list(rdr)
        return rows, list(rdr.fieldnames or [])


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8-sig") as fh:
        return list(csv.DictReader(fh))


def write_csv(path: Path, header: list[str], rows: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=header, lineterminator="\n")
        w.writeheader()
        for r in rows:
            missing = [k for k in header if k not in r]
            if missing:
                raise SystemExit(f"{path.name}: row {r.get('row_id') or r.get('evidence_id') or r.get('census_id')} "
                                 f"missing keys {missing}")
            extra = [k for k in r if k not in header]
            if extra:
                raise SystemExit(f"{path.name}: unexpected keys {extra}")
            w.writerow(r)
    print(f"  wrote {path.relative_to(ROOT)}: {len(rows)} rows")


def rel_of(rec: dict) -> str:
    """Row id of an era-audit record, for the tracked-in cell."""
    return rec.get("row_id", "")


def manifest_index(path: Path) -> dict:
    """Map out-file -> manifest entry, for SHA re-verification."""
    if not path.exists():
        return {}
    m = json.loads(path.read_text(encoding="utf-8"))
    out: dict = {}
    for e in m.get("requests", []):
        if e.get("out"):
            out[e["out"]] = e
    return out


def main() -> int:
    print(f"== {V28} pre-1939 boundary build ==")
    errors: list[str] = []

    for p in (APPS_ALL, SUBS_1938_64, SUBS_1965_79, APPS_1938_64, V27_REGISTER,
              V27_1938_DET, OFFICIAL_SERIES):
        if not p.exists():
            print(f"FAIL: required input missing: {p.relative_to(ROOT)}")
            return 2

    # ---- SHA-256 of every committed input, checked against its runner manifest
    sha_apps_all = sha256_file(APPS_ALL)
    sha_subs_1938_64 = sha256_file(SUBS_1938_64)
    sha_subs_1965_79 = sha256_file(SUBS_1965_79)

    man_2026_09 = manifest_index(RAW_2026_09 / "manifest.json")
    man_1938_64 = manifest_index(RAW_1938_64 / "manifest.json")
    if not man_2026_09 or not man_1938_64:
        print("FAIL: runner manifests missing - cannot re-verify input SHA-256")
        return 2
    for label, path, sha, man in (
        ("Applications_all_types.txt", APPS_ALL, sha_apps_all, man_2026_09),
        ("Submissions_1938_1964.txt", SUBS_1938_64, sha_subs_1938_64, man_1938_64),
        ("Submissions_1965_1979.txt", SUBS_1965_79, sha_subs_1965_79, man_2026_09),
    ):
        entries = [e for e in man.values() if e.get("out") == path.name]
        if not entries:
            errors.append(f"{label}: not present in its runner manifest")
            continue
        rec = entries[0]
        # Applications_all_types is an unfiltered FULL member: out == member.
        want = rec.get("out_sha256") or rec.get("member_sha256")
        if want != sha:
            errors.append(f"{label}: SHA-256 drift vs runner manifest "
                          f"({sha[:16]} != {str(want)[:16]})")
    if errors:
        print("\n".join(f"FAIL {e}" for e in errors))
        return 1

    # ---- load the official tables -------------------------------------------
    apps_all, apps_all_hdr = read_tsv(APPS_ALL)
    if len(apps_all) != EXPECTED_APPS_TOTAL:
        print(f"FAIL: Applications_all_types.txt has {len(apps_all)} rows, "
              f"expected {EXPECTED_APPS_TOTAL}")
        return 1
    subs_1938_64, _ = read_tsv(SUBS_1938_64)
    subs_1965_79, _ = read_tsv(SUBS_1965_79)
    print(f"  official application map: {len(apps_all)} rows")
    print(f"  official Submissions windows: {len(subs_1938_64)} (1938-1964), "
          f"{len(subs_1965_79)} (1965-1979)")

    # ---- 1. application-number census below the boundary ---------------------
    low_apps = [a for a in apps_all
                if a["ApplNo"].strip().isdigit()
                and int(a["ApplNo"]) < BOUNDARY_APPLNO]
    low_apps.sort(key=lambda a: int(a["ApplNo"]))
    low_applnos = [a["ApplNo"].strip() for a in low_apps]
    print(f"  applications numbered below NDA{BOUNDARY_APPLNO:06d}: {low_applnos}")
    if not low_applnos:
        print("FAIL: the official application map has no application below the "
              "boundary - the boundary claim cannot be reproduced")
        return 1

    all_subs = {**{("1938-1964", i): r for i, r in enumerate(subs_1938_64)},
                **{("1965-1979", i): r for i, r in enumerate(subs_1965_79)}}
    subs_by_appl: dict[str, list[tuple[str, dict]]] = {a: [] for a in low_applnos}
    for (win, _i), r in all_subs.items():
        ap = r["ApplNo"].strip()
        if ap in subs_by_appl:
            subs_by_appl[ap].append((win, r))

    # Where is a below-boundary application already tracked inside this project?
    # Looked up by application number in the SHA-verified era audit tables, in
    # era order - never assumed. NME-comparable rows live in the era *decision*
    # tables; non-NME originals live only in the era *audit* tables, and saying
    # otherwise is the kind of unverified claim the verifier is there to catch.
    ERA_TABLES = [
        ("data/pre1965_originals_audit_1939_1964.csv", "pre-1965 originals audit (1939-1964)"),
        ("data/pre1980_originals_audit_1965_1976.csv", "pre-1980 originals audit (1965-1976)"),
        ("data/pre1980_originals_audit_1977_1979.csv", "pre-1980 originals audit (1977-1979)"),
    ]
    era_index: dict[str, tuple[dict, str]] = {}
    for rel, label in ERA_TABLES:
        pth = DATA / rel.split("/")[-1]
        if not pth.exists():
            print(f"  note: era table {rel} absent - skipped")
            continue
        for r in read_csv(pth):
            era_index.setdefault(r["application_number"], (r, label))
    print(f"  era-audit index: {len(era_index)} applications across {len(ERA_TABLES)} era tables")

    census_rows: list[dict] = []
    for i, a in enumerate(low_apps, 1):
        ap = a["ApplNo"].strip()
        number = f"NDA{ap}" if a["ApplType"].strip().upper() == "NDA" else \
                 f"{a['ApplType'].strip().upper()}{ap}"
        rows = sorted(subs_by_appl[ap],
                      key=lambda t: (t[1]["SubmissionStatusDate"], t[1]["SubmissionType"],
                                     t[1]["SubmissionNo"]))
        dates = [r["SubmissionStatusDate"].strip() for _w, r in rows]
        earliest = min(dates) if dates else ""
        latest = max(dates) if dates else ""
        pre1939 = [d for d in dates if d[:4].isdigit() and int(d[:4]) < 1939]
        verbatim = " | ".join(
            f"[{w}] ApplNo={r['ApplNo']} class={r['SubmissionClassCodeID'] or '(blank)'} "
            f"type={r['SubmissionType']} no={r['SubmissionNo']} status={r['SubmissionStatus']} "
            f"date={r['SubmissionStatusDate']} priority={r['ReviewPriority'] or '(blank)'}"
            for w, r in rows) or "(no submission row in the committed windows)"
        flags = []
        if not rows:
            flags.append("FLAG-NO-SUBMISSION-ROW-IN-COMMITTED-WINDOWS")
        if ap == "000004":
            # Documented irregularity: the lowest-numbered application in the
            # official database carries an application number issued at the
            # start of NDA numbering, yet its only recorded approval action in
            # the committed official windows is dated 1969-07-16 - i.e. it is a
            # 1969 decision, not a 1938/1939 one. Never "corrected".
            flags.append("FLAG-LOWEST-APPLNO-APPROVED-1969")
        era_rec, era_label = era_index.get(number, ({}, ""))
        tracked = f"{era_label} ({rel_of(era_rec)})" if era_rec else \
            "none - not present in any committed era audit table"
        census_rows.append({
            "census_id": f"PRE1939CENSUS-{i:03d}",
            "appl_no": ap,
            "application_number": number,
            "appl_type": a["ApplType"].strip(),
            "sponsor_name_official_db": a["SponsorName"].strip(),
            "appl_public_notes": a["ApplPublicNotes"].strip(),
            "in_official_applications_map": "True",
            "n_submission_rows_committed_windows": str(len(rows)),
            "submission_rows_verbatim": verbatim,
            "earliest_recorded_action_date": earliest,
            "latest_recorded_action_date": latest,
            "decision_recorded_before_1939": "False" if not pre1939 else f"True ({', '.join(sorted(pre1939))})",
            "first_product_brand_official_payload": era_rec.get("first_product_brand", ""),
            "first_product_ingredients": era_rec.get("first_product_ingredients", ""),
            "first_product_form_route": era_rec.get("first_product_form_route", ""),
            "first_product_marketing_status": era_rec.get("first_product_marketing_status", ""),
            "nme_comparable": era_rec.get("nme_comparable", ""),
            "tracked_in_project_table": tracked,
            "project_table_row_id": era_rec.get("row_id", ""),
            "drugsatfda_url": DRUGSATFDA.format(appl=ap),
            "source_file": ("data/raw/drugsatfda_data_files_2026_09/Applications_all_types.txt; "
                            "data/raw/drugsatfda_data_files_1938_1964/Submissions_1938_1964.txt; "
                            "data/raw/drugsatfda_data_files_2026_09/Submissions_1965_1979.txt"),
            "source_url": DRUGSATFDA.format(appl=ap),
            "verification_status": ("Verified - verbatim from the unfiltered official Drugs@FDA "
                                    "application map and the official Submissions windows "
                                    f"({V28})"),
            "flags": "; ".join(flags),
            "notes": (
                f"Official Drugs@FDA application {number} is one of {len(low_apps)} applications "
                f"in the {len(apps_all)}-row unfiltered official application map numbered below "
                f"NDA{BOUNDARY_APPLNO:06d} (the application carrying the first recorded FDA drug "
                "approval action, 1939-02-09). Sponsor name is the Drugs@FDA holder of record; no "
                "ticker, exchange, indication or approval-era corporate lineage is asserted. "
                f"Recorded submission actions in the committed official windows: {len(rows)}. "
                f"Product fields (when present) are verbatim from the committed SHA-verified "
                f"openFDA era payload via {era_label or 'no era table'}."
            ),
        })

    # ---- 2. boundary facts --------------------------------------------------
    yrs_1938_64 = Counter(r["SubmissionStatusDate"][:4] for r in subs_1938_64)
    n_1938 = yrs_1938_64.get("1938", 0)
    dates_1938_64 = sorted(r["SubmissionStatusDate"] for r in subs_1938_64)
    earliest = dates_1938_64[0]
    earliest_rows = [r for r in subs_1938_64 if r["SubmissionStatusDate"] == earliest]
    earliest_applnos = sorted({r["ApplNo"].strip() for r in earliest_rows})
    st_1938_64 = Counter(r["SubmissionStatus"] for r in subs_1938_64)
    ty_1938_64 = Counter(r["SubmissionType"] for r in subs_1938_64)
    st_1965_79 = Counter(r["SubmissionStatus"] for r in subs_1965_79)
    ty_1965_79 = Counter(r["SubmissionType"] for r in subs_1965_79)

    if n_1938 != 0:
        errors.append(f"1938 rows appeared in the official 1938-1964 Submissions window ({n_1938})")
    if earliest != EARLIEST_DATE:
        errors.append(f"earliest official submission date is {earliest}, expected {EARLIEST_DATE}")
    if earliest_applnos != [EARLIEST_APPLNO]:
        errors.append(f"earliest official submission date is not on ApplNo {EARLIEST_APPLNO}: {earliest_applnos}")
    if set(st_1938_64) != {"AP"}:
        errors.append(f"1938-1964 window statuses are not all AP: {dict(st_1938_64)}")
    if set(st_1965_79) != {"AP"}:
        errors.append(f"1965-1979 window statuses are not all AP: {dict(st_1965_79)}")
    if errors:
        print("\n".join(f"FAIL {e}" for e in errors))
        return 1
    print(f"  boundary: 0 rows dated 1938; earliest official action {earliest} on "
          f"ApplNo {EARLIEST_APPLNO}; statuses 1938-1964={dict(st_1938_64)}, "
          f"1965-1979={dict(st_1965_79)}")

    # ---- openFDA payload block starts at 1939 ------------------------------
    payload_years = sorted(int(p.stem.replace("decisions_", ""))
                           for p in PAYLOAD_DIR.glob("decisions_*.json"))
    if not payload_years or payload_years[0] != 1939:
        print(f"FAIL: openFDA payload block does not start at 1939: {payload_years[:3]}")
        return 1
    payload_manifest = json.loads((PAYLOAD_DIR / "manifest.json").read_text(encoding="utf-8"))
    p1939 = next((e for e in payload_manifest["requests"] if e.get("id") == "orig_decisions_1939"), None)
    if p1939 is None:
        print("FAIL: orig_decisions_1939 entry missing from the payload manifest")
        return 1
    sha_1939 = sha256_file(PAYLOAD_DIR / "decisions_1939.json")
    if p1939.get("sha256") != sha_1939:
        print(f"FAIL: decisions_1939.json SHA drift ({sha_1939[:16]} != {str(p1939.get('sha256'))[:16]})")
        return 1

    # ---- v27 register reproduces the official extract row-for-row -----------
    v27_reg = read_csv(V27_REGISTER)
    def k_raw(r):
        return (r["ApplNo"], r["SubmissionType"], r["SubmissionNo"],
                r["SubmissionStatus"], r["SubmissionStatusDate"])
    def k_csv(r):
        return (r["appl_no"], r["submission_type"], r["submission_number"],
                r["submission_status"], r["submission_status_date"])
    if Counter(map(k_raw, subs_1938_64)) != Counter(map(k_csv, v27_reg)):
        print("FAIL: data/fda_1938_1964_full_submission_register.csv no longer "
              "reproduces the official extract row-for-row")
        return 1
    if Counter(r["submission_status"] for r in v27_reg) != {"AP": len(v27_reg)}:
        print("FAIL: v27 register statuses drifted from all-AP")
        return 1
    print(f"  v27 register re-verified: {len(v27_reg)} rows reproduce the official extract "
          f"({dict(Counter(r['submission_type'] for r in v27_reg))}, all status AP)")

    # ---- optional runner captures ------------------------------------------
    census_present = False
    man_census = manifest_index(RAW_CENSUS / "manifest.json")
    capture: dict[str, dict] = {}
    if man_census:
        census_present = True
        for out_name, entry in man_census.items():
            p = RAW_CENSUS / out_name
            if not p.exists():
                errors.append(f"census capture {out_name} recorded in the manifest but absent")
                continue
            got = sha256_file(p)
            if entry.get("sha256") != got:
                errors.append(f"census capture {out_name}: SHA-256 drift vs manifest")
                continue
            rows, _h = read_tsv(p)
            capture[out_name] = {"rows": rows, "meta": entry}
        if errors:
            print("\n".join(f"FAIL {e}" for e in errors))
            return 1
        # cross-check every captured fact against what the windows already imply
        b = capture.get("Submissions_before_1939.txt", {}).get("rows", [])
        if b:
            errors.append(f"official table contains {len(b)} submission rows dated before 1939 - "
                          f"the 1939 boundary is wrong; first rows: {b[:3]}")
        low_cap = capture.get("Applications_below_boundary.txt", {}).get("rows", [])
        cap_set = sorted(r["ApplNo"].strip() for r in low_cap)
        if cap_set != sorted(low_applnos):
            errors.append(f"captured below-boundary application census {cap_set} != "
                          f"map-derived {sorted(low_applnos)}")
        sub_cap = capture.get("Submissions_applno_below_boundary.txt", {}).get("rows", [])
        cap_keys = Counter((r["ApplNo"], r["SubmissionType"], r["SubmissionNo"],
                            r["SubmissionStatus"], r["SubmissionStatusDate"]) for r in sub_cap)
        win_keys = Counter()
        for ap, rows in subs_by_appl.items():
            for _w, r in rows:
                win_keys[(r["ApplNo"], r["SubmissionType"], r["SubmissionNo"],
                          r["SubmissionStatus"], r["SubmissionStatusDate"])] += 1
        if cap_keys != win_keys:
            # Not fatal by itself - the capture is COMPLETE history, the windows
            # are not - but a row present in a window and absent from the full
            # history would be a contradiction.
            missing = win_keys - cap_keys
            if missing:
                errors.append(f"window rows absent from the complete official history: "
                              f"{list(missing.items())[:3]}")
        st = capture.get("Submissions_status_counts.txt", {}).get("rows", [])
        if st and [r["SubmissionStatus"] for r in st] != ["AP"]:
            errors.append(f"official Submissions table publishes non-AP statuses: {st}")
        if errors:
            print("\n".join(f"FAIL {e}" for e in errors))
            return 1
        print(f"  runner captures joined: {sorted(capture)}")
    else:
        print("  runner capture layer pending (fetch_jobs/drugsatfda_pre1939_census_v28.json "
              "has not landed yet) - window-derived facts only, stated as such")

    # ---- 3. evidence table --------------------------------------------------
    def ev(i, cat, claim, method, observed, src_file, sha, url, status, notes):
        return {"evidence_id": f"PRE1939EV-{i:02d}", "category": cat, "claim": claim,
                "method": method, "observed_value": observed, "source_file": src_file,
                "source_sha256_prefix": sha[:16] if sha else "", "source_url": url,
                "verification_status": status, "notes": notes}

    boundary_rows: list[dict] = []
    boundary_rows.append(ev(
        1, "application-number census",
        f"The official Drugs@FDA application map contains exactly {len(low_apps)} applications "
        f"numbered below NDA{BOUNDARY_APPLNO:06d}",
        f"Enumerated all {len(apps_all)} rows of the unfiltered official application map and "
        f"selected ApplNo < {BOUNDARY_APPLNO} (numeric)",
        f"{len(low_apps)} applications: {', '.join(low_applnos)}",
        "data/raw/drugsatfda_data_files_2026_09/Applications_all_types.txt",
        sha_apps_all, "https://www.fda.gov/media/89850/download?attachment",
        "Verified - complete enumeration of the official map",
        "Applications 000001-000003 and 000005-000158 do not exist in the official database at all. "
        "The census is therefore exhaustive, not a sample."))
    boundary_rows.append(ev(
        2, "application-number census",
        "NDA000004 (PHARMICS) is the lowest-numbered application in the official database",
        "Verbatim row copy from the official application map and the official Submissions windows",
        "ApplNo 000004, ApplType NDA, SponsorName PHARMICS; recorded submission action: "
        "ORIG 1, status AP, 1969-07-16 (class 19, priority UNKNOWN)",
        "data/raw/drugsatfda_data_files_2026_09/Submissions_1965_1979.txt",
        sha_subs_1965_79, DRUGSATFDA.format(appl="000004"),
        "Verified - verbatim from the official data files",
        "FLAGGED irregularity, never corrected: the lowest application number carries a 1969 "
        "approval action, not a 1938/1939 one. NDA numbering began with the 1938 FD&C Act, but "
        "the official database records no 1938 action for this application. Product of record "
        "(committed openFDA payload): PAREDRINE, hydroxyamphetamine hydrobromide 1% "
        "ophthalmic solution/drops, marketing status Discontinued, submission class UNKNOWN. "
        "It is therefore a 1969 non-NME-comparable original, tracked in "
        "data/pre1980_originals_audit_1965_1976.csv row PRE1980AUDIT-1969-10 - NOT in "
        "data/pre1980_fda_decisions.csv, which holds only Type 1 / Type 1-4 NME rows."))
    boundary_rows.append(ev(
        3, "application-number census",
        "NDA000159 (LILLY) is the other application numbered below the boundary",
        "Verbatim row copy from the official application map and the official Submissions windows",
        "ApplNo 000159, ApplType NDA, SponsorName LILLY; recorded submission action: "
        "ORIG 1, status AP, 1939-03-09 (class blank, priority blank)",
        "data/raw/drugsatfda_data_files_1938_1964/Submissions_1938_1964.txt",
        sha_subs_1938_64, DRUGSATFDA.format(appl="000159"),
        "Verified - verbatim from the official data files",
        "A 1939 decision, already counted in data/pre1965_fda_decisions.csv."))
    boundary_rows.append(ev(
        4, "boundary date",
        "The earliest FDA drug-approval action recorded in the official database is 1939-02-09",
        f"Minimum SubmissionStatusDate over all {len(subs_1938_64)} rows of the official "
        "1938-1964 Submissions window",
        f"{earliest} on ApplNo {EARLIEST_APPLNO} "
        f"({', '.join(sorted({r['SubmissionType'] + ' ' + r['SubmissionNo'] for r in earliest_rows}))}, "
        f"status AP, class {earliest_rows[0]['SubmissionClassCodeID'] or '(blank)'})",
        "data/raw/drugsatfda_data_files_1938_1964/Submissions_1938_1964.txt",
        sha_subs_1938_64, DRUGSATFDA.format(appl=EARLIEST_APPLNO),
        "Verified - minimum over the committed official extract",
        "NDA000552 is the first heparin NDA (LIQUAEMIN SODIUM, Aspen Global Inc.), independently "
        "confirmed in the v26 era table by Federal Register 91 FR (2026-03-09)."))
    boundary_rows.append(ev(
        5, "boundary date",
        "0 submission actions are dated in 1938 in the official database window",
        f"Counted rows whose SubmissionStatusDate year == 1938 among all {len(subs_1938_64)} "
        "rows of the official 1938-1964 Submissions window",
        "0 rows (year distribution starts at 1939: 15 rows)",
        "data/raw/drugsatfda_data_files_1938_1964/Submissions_1938_1964.txt",
        sha_subs_1938_64, "https://www.fda.gov/media/89850/download?attachment",
        "Verified - complete count over the committed official extract",
        "Re-verifies data/pre1938_determination.csv line by line. Scope caveat, stated not "
        "smoothed: this counts rows whose status date parses to 1938; rows with an empty or "
        "unparseable status date are invisible to any year filter, so the queued runner job "
        "fetch_jobs/drugsatfda_pre1939_census_v28.json counts those separately "
        "(Submissions_undated.txt) and counts every row dated before 1939 anywhere in the "
        "193,752-row official table (Submissions_before_1939.txt)."))
    boundary_rows.append(ev(
        6, "payload coverage",
        "The committed openFDA Drugs@FDA decision payloads start at 1939",
        "Enumerated decisions_*.json in the payload block and re-hashed decisions_1939.json "
        "against its runner manifest entry",
        f"{len(payload_years)} payload years {payload_years[0]}-{payload_years[-1]}; "
        f"decisions_1939.json sha256 {sha_1939[:16]}... ({p1939.get('decisions')} decisions); "
        "no decisions_1938.json exists",
        "data/raw/openfda_orig_decisions_1939_1964/", sha_1939,
        "https://api.fda.gov/drug/drugsfda.json?search=submissions.submission_type:%22ORIG%22"
        "%20AND%20submissions.submission_status:%22AP%22%20AND%20submissions.submission_status_date:"
        "[19390101%20TO%2019391231]&limit=1000&skip=0",
        "Verified - SHA-256 matches the runner manifest",
        "The openFDA Drugs@FDA extract is the same source of record used for every era block in "
        "this repository."))
    boundary_rows.append(ev(
        7, "official series",
        "FDA's official NDA series starts in 1938 and publishes 1938-1940 only combined",
        "Read the committed official-series table (FDA 'Summary of NDA approvals and receipts, "
        "1938-present'), rows 1938-1940",
        "1938: no figure published; 1939: no figure published; 1940: '1782 (1938-40)' NDAs "
        "approved, '14 (1940 only)' NMEs, '2752 (1938-40)' received",
        "data/fda_official_year_series.csv", "", SRC_FDA_SERIES,
        "Verified - verbatim from the FDA official series",
        "There is no official per-year NDA/NME figure for 1938 or 1939 anywhere in FDA's series, "
        "so no 1938 count can be asserted without inventing one."))
    boundary_rows.append(ev(
        8, "non-approval decisions",
        "The official Drugs@FDA Submissions table publishes approval actions only - it does not "
        "contain refused (RE) or withdrawn (W) decisions",
        f"Counted distinct SubmissionStatus values over both committed official windows "
        f"({len(subs_1938_64)} rows 1938-1964 and {len(subs_1965_79)} rows 1965-1979)",
        f"1938-1964: {dict(st_1938_64)}; 1965-1979: {dict(st_1965_79)} "
        f"(submission types 1938-1964: {dict(ty_1938_64)}; 1965-1979 types: {dict(ty_1965_79)})",
        "data/raw/drugsatfda_data_files_1938_1964/Submissions_1938_1964.txt; "
        "data/raw/drugsatfda_data_files_2026_09/Submissions_1965_1979.txt",
        sha_subs_1938_64, "https://www.fda.gov/media/89850/download?attachment",
        "Verified - complete count over the committed official extracts",
        "CORRECTION to the v27 site/README copy, which described the 1938-1964 register as "
        "'ORIG/AP plus RE, W, etc.' and said 'this is where non-approval decisions "
        "(rejections/withdrawals) live'. Every one of the 1,215 rows has submission_status AP. "
        "Non-approval FDA decisions are not obtainable from Drugs@FDA Submissions.txt; the "
        "project's CRL evidence comes from FDA's separate CRL database "
        "(data/fda_crl_master.csv, 458 rows). The whole-table status census is queued in "
        "fetch_jobs/drugsatfda_pre1939_census_v28.json to close the remaining scope caveat."))
    boundary_rows.append(ev(
        9, "statutory framework",
        "No federal pre-market drug approval system existed before 1938",
        "Read the 1906 Food and Drugs Act in full (U.S. Statutes at Large via govinfo.gov)",
        "The 1906 Act prohibits manufacturing/interstate shipment of adulterated or misbranded "
        "drugs and enforces by notice, certification to the district attorney, seizure and "
        "criminal penalty. It creates no application, no filing and no approval. Examinations "
        "are assigned to the Bureau of Chemistry, Department of Agriculture (Sec. 4).",
        "(external primary source)", "", SRC_1906,
        "Verified - statute text retrieved and read from govinfo.gov",
        "Consequence for this project: there is no such thing as an 'FDA approval decision' "
        "before the 1938 FD&C Act, so a pre-1938 decision table would necessarily be invented. "
        "None is written."))
    boundary_rows.append(ev(
        10, "statutory framework",
        "Federal pre-market LICENSURE of one drug class predates the FDA by 36 years",
        "Read the Biologics Control Act of 1902 in full (U.S. Statutes at Large via govinfo.gov)",
        "From six months after the regulations were promulgated, no virus, therapeutic serum, "
        "toxin, antitoxin or analogous product for the prevention and cure of human disease may "
        "be sold in or shipped into the District of Columbia or across state lines unless made "
        "at an establishment holding an unsuspended, unrevoked license issued by the Secretary "
        "of the Treasury, and unless each package bears the proper name, manufacturer name, "
        "address, license number and an expiration date.",
        "(external primary source)", "", SRC_1902,
        "Verified - statute text retrieved and read from govinfo.gov",
        "This is the only pre-1938 federal drug pre-market authorisation regime. It was "
        "administered by the Public Health Service, not by FDA; biologics authority moved to FDA "
        "in 1972. No official machine-readable census of individual 1902-1938 licenses is "
        "published, so no per-license rows are asserted anywhere in this repository - "
        "documented as an open data gap, not filled by inference."))
    boundary_rows.append(ev(
        11, "statutory framework",
        "The new-drug application was created by the 1938 FD&C Act",
        "Read the enacting chapter in the U.S. Statutes at Large (govinfo.gov) and the current "
        "codification at 21 U.S.C. 355(a)",
        "Act of June 25, 1938, ch. 675, 52 Stat. 1040; Sec. 1: 'This Act may be cited as the "
        "Federal Food, Drug, and Cosmetic Act.' Now 21 U.S.C. 355(a): 'No person shall introduce "
        "or deliver for introduction into interstate commerce any new drug, unless an approval "
        "of an application filed pursuant to subsection (b) or (j) is effective with respect to "
        "such drug.'",
        "(external primary source)", "", SRC_1938,
        "Verified - statute text and codification retrieved and read",
        "This is why the project's verified decision coverage begins in 1939: the application "
        "system itself began in 1938, and the official database's first recorded action is "
        "1939-02-09. 21 U.S.C. 355 codification read at " + SRC_USC355))
    if census_present:
        b = capture.get("Submissions_before_1939.txt", {})
        u = capture.get("Submissions_undated.txt", {})
        st = capture.get("Submissions_status_counts.txt", {})
        ty = capture.get("Submissions_type_counts.txt", {})
        boundary_rows.append(ev(
            len(boundary_rows) + 1, "complete-table census (runner capture)",
            "The complete official Submissions table contains no row dated before 1939",
            "Runner capture: date_year_before 1939 over every row of Submissions.txt "
            f"({b.get('meta', {}).get('rows_total')} rows in the member)",
            f"{len(b.get('rows', []))} rows dated before 1939; "
            f"{len(u.get('rows', []))} rows with an empty/unparseable status date "
            f"(of {u.get('meta', {}).get('rows_total')} member rows); "
            f"status census {[ (r['SubmissionStatus'], r['count']) for r in st.get('rows', []) ]}; "
            f"type census {[ (r['SubmissionType'], r['count']) for r in ty.get('rows', []) ]}",
            "data/raw/drugsatfda_pre1939_census_v28/",
            b.get("meta", {}).get("member_sha256", ""),
            "https://www.fda.gov/media/89850/download?attachment",
            "Verified - complete official table, not a year-filtered window",
            "Closes the year-filter scope caveat: the 0-rows-in-1938 finding now holds over all "
            "193,752 rows of the official table, and the undated-row count states exactly how "
            "many rows no year filter could ever see."))
    else:
        boundary_rows.append(ev(
            len(boundary_rows) + 1, "complete-table census (runner capture)",
            "Whole-table census pending: rows dated before 1939, undated rows, and the "
            "SubmissionStatus / SubmissionType census of the complete official table",
            "Queued runner job fetch_jobs/drugsatfda_pre1939_census_v28.json (zip_extract of the "
            "official Drugs@FDA data files, five recorded row selectors over Submissions.txt and "
            "Applications.txt)",
            "PENDING - capture has not landed; the boundary rests on the two committed "
            "year-filtered windows (1,215 + 10,753 rows) until it does",
            "fetch_jobs/drugsatfda_pre1939_census_v28.json", "",
            "https://www.fda.gov/media/89850/download?attachment",
            "Pending runner capture - scope caveat stated, not smoothed",
            "This row deliberately does not claim the whole-table result. It records what is "
            "still outstanding so the boundary claim cannot be over-read."))

    # ---- 4. per-year submission status census -------------------------------
    status_rows: list[dict] = []
    n = 0
    for label, rows, sha, src in (
        ("1938-1964 official window", subs_1938_64, sha_subs_1938_64,
         "data/raw/drugsatfda_data_files_1938_1964/Submissions_1938_1964.txt"),
        ("1965-1979 official window", subs_1965_79, sha_subs_1965_79,
         "data/raw/drugsatfda_data_files_2026_09/Submissions_1965_1979.txt"),
    ):
        by_year: dict[str, list[dict]] = {}
        for r in rows:
            by_year.setdefault(r["SubmissionStatusDate"][:4], []).append(r)
        for y in sorted(by_year):
            grp = by_year[y]
            n += 1
            statuses = sorted({r["SubmissionStatus"] for r in grp})
            types = Counter(r["SubmissionType"] for r in grp)
            non_ap = sum(1 for r in grp if r["SubmissionStatus"] != "AP")
            status_rows.append({
                "census_id": f"PRE1939STATUS-{n:03d}",
                "source_window": label,
                "year": y,
                "total_rows": str(len(grp)),
                "orig_ap_rows": str(types.get("ORIG", 0)),
                "suppl_ap_rows": str(types.get("SUPPL", 0)),
                "other_type_rows": str(len(grp) - types.get("ORIG", 0) - types.get("SUPPL", 0)),
                "distinct_statuses": "|".join(statuses),
                "non_ap_rows": str(non_ap),
                "determination": ("All recorded actions are approvals (AP). The official "
                                  "Drugs@FDA Submissions table publishes no refused (RE) or "
                                  "withdrawn (W) actions, so non-approval decisions for this "
                                  "year are not obtainable from this source."),
                "source_file": src,
                "source_sha256_prefix": sha[:16],
                "source_url": "https://www.fda.gov/media/89850/download?attachment",
                "verification_status": ("Verified - complete count over the committed official "
                                        f"extract ({V28})"),
                "notes": (f"Per-year census of the official Drugs@FDA Submissions extract, "
                          f"{label}. Counts recomputed verbatim from the extract; "
                          f"orig_ap + suppl_ap + other = total_rows on every row."),
            })
    for r in status_rows:
        if int(r["orig_ap_rows"]) + int(r["suppl_ap_rows"]) + int(r["other_type_rows"]) != int(r["total_rows"]):
            print(f"FAIL: status census row {r['census_id']} does not sum")
            return 1

    # ---- 5. regulatory register 1902-1938 ----------------------------------
    series = {r["year"]: r for r in read_csv(OFFICIAL_SERIES)}

    def series_cov(y: str) -> str:
        r = series.get(y)
        if r is None:
            return ("Not covered - FDA's official 'Summary of NDA approvals and receipts, "
                    "1938-present' series begins in 1938")
        ndas, nmes, rec = (r.get("ndas_approved") or "").strip(), (r.get("nmes_approved") or "").strip(), (r.get("ndas_received") or "").strip()
        if not (ndas or nmes or rec):
            return ("FDA's official series lists this year but publishes no figure for it "
                    "(1938-1940 are published combined, on the 1940 row)")
        return (f"FDA official series: NDAs approved {ndas or 'n/a'}, NMEs approved "
                f"{nmes or 'n/a'}, NDAs received {rec or 'n/a'}")

    REG_1906 = ("Pure Food and Drugs Act, Act of June 30, 1906, ch. 3915, 34 Stat. 768")
    REG_1906_AMENDED = ("Pure Food and Drugs Act of 1906 (ch. 3915, 34 Stat. 768) as amended by "
                        "the Sherley Amendment, Act of Aug. 23, 1912, ch. 352, 37 Stat. 416")
    EVENTS = {
        1902: ("Biologics Control Act enacted July 1, 1902",
               "Public Health Service, U.S. Treasury Department (Hygienic Laboratory)",
               "Federal pre-market LICENSURE of biologics: establishment license issued by the "
               "Secretary of the Treasury, plus package labeling of proper name, manufacturer, "
               "license number and expiration date. No approval system for drugs generally.",
               "Act of July 1, 1902, ch. 1378, Pub. L. 57-244, 32 Stat. 728", "1902-07-01",
               QUOTE_1902, SRC_1902, SRC_USC355, ""),
        1906: ("Pure Food and Drugs Act enacted June 30, 1906",
               "Bureau of Chemistry, U.S. Department of Agriculture",
               "NO pre-market approval. Prohibition on manufacturing or shipping adulterated or "
               "misbranded drugs in interstate commerce; enforcement by notice, certification to "
               "the U.S. district attorney, seizure and criminal penalty.",
               REG_1906, "1906-06-30", QUOTE_1906, SRC_1906, SRC_USC355, ""),
        1912: ("Sherley Amendment enacted August 23, 1912",
               "Bureau of Chemistry, U.S. Department of Agriculture",
               "Still no pre-market approval. Adds false-and-fraudulent therapeutic claims as a "
               "ground of misbranding, so therapeutic claims become actionable.",
               "Act of Aug. 23, 1912, ch. 352, 37 Stat. 416", "1912-08-23",
               QUOTE_1912, SRC_1912, SRC_1906, ""),
        1927: ("Bureau of Chemistry reorganised; regulatory wing becomes the Food, Drug, and "
               "Insecticide Administration",
               "Food, Drug, and Insecticide Administration, U.S. Department of Agriculture",
               "No pre-market approval. Same 1906 Act enforcement regime under the new agency name.",
               REG_1906_AMENDED, "", QUOTE_FDA_HISTORY, SRC_FDA_HISTORY, SRC_1912, ""),
        1930: ("Agency name shortened to Food and Drug Administration",
               "Food and Drug Administration, U.S. Department of Agriculture",
               "No pre-market approval. Same 1906 Act enforcement regime.",
               REG_1906_AMENDED, "", QUOTE_FDA_HISTORY, SRC_FDA_HISTORY, SRC_1912, ""),
        1937: ("Elixir Sulfanilamide deaths; FDA reports to Congress",
               "Food and Drug Administration, U.S. Department of Agriculture",
               "No pre-market approval. The deaths were caused by an untested solvent "
               "(diethylene glycol) that the 1906 Act did not require anyone to prove safe "
               "before marketing - the direct trigger for the 1938 Act.",
               REG_1906_AMENDED, "",
               "FDA history: 'So-called Elixir Sulfanilamide employed an untested solvent for the "
               "drug, diethylene glycol, and eventually it killed over a hundred people, most of "
               "whom were children.'",
               SRC_FDA_HISTORY, SRC_1912, ""),
        1938: ("Federal Food, Drug, and Cosmetic Act enacted June 25, 1938 - creates the "
               "new-drug application",
               "Food and Drug Administration, U.S. Department of Agriculture",
               "Pre-market approval created for new drugs generally: an application must be filed "
               "and become effective before interstate commerce. NDA numbering begins.",
               "Act of June 25, 1938, ch. 675, Pub. L. 75-717, 52 Stat. 1040", "1938-06-25",
               QUOTE_1938, SRC_1938, SRC_USC355, SRC_FDA_SERIES),
    }
    DEFAULT_AGENCY_PRE1906 = "Bureau of Chemistry, U.S. Department of Agriculture"

    def agency_for(y: int) -> str:
        if y < 1906:
            return "Public Health Service, U.S. Treasury Department (biologics licensure only)"
        if y < 1927:
            return DEFAULT_AGENCY_PRE1906
        if y < 1930:
            return "Food, Drug, and Insecticide Administration, U.S. Department of Agriculture"
        return "Food and Drug Administration, U.S. Department of Agriculture"

    def regime_for(y: int) -> str:
        base = ("No general federal pre-market drug approval. Biologics required an establishment "
                "license under the Biologics Control Act of 1902; all other drugs were unapproved "
                "by default and regulated only against adulteration and misbranding.")
        if y < 1906:
            return ("No federal drug law of general application. Biologics required an "
                    "establishment license under the Biologics Control Act of 1902.")
        if y < 1912:
            return base + " (1906 Act)."
        return base + " (1906 Act as amended by the 1912 Sherley Amendment)."

    register_rows: list[dict] = []
    for i, y in enumerate(range(1902, 1939), 1):
        ys = str(y)
        ev_entry = EVENTS.get(y)
        if ev_entry:
            landmark, agency, regime, citation, enacted, quote, u1, u2, u3 = ev_entry
        else:
            landmark = ""
            agency = agency_for(y)
            regime = regime_for(y)
            citation = REG_1906 if y < 1912 else REG_1906_AMENDED
            enacted = "1906-06-30" if y < 1912 else "1912-08-23"
            quote = QUOTE_1906 if y < 1912 else QUOTE_1912
            u1 = SRC_1906 if y < 1912 else SRC_1912
            u2 = SRC_1906 if y >= 1912 else SRC_1902
            u3 = ""
        if y == 1938:
            determination = ("0 FDA drug-approval decision rows recorded. Verified negative, "
                             "re-derived this session: 0 of the 1,215 rows in the official "
                             "1938-1964 Submissions window are dated in 1938, and no "
                             "decisions_1938.json exists in the openFDA payload block. See "
                             "data/pre1938_determination.csv. No 1938 row is invented.")
            basis = ("Counted rows dated 1938 in the official Drugs@FDA Submissions extract "
                     "(1,215 rows, 0 in 1938) and enumerated the committed openFDA payloads "
                     "(earliest decisions_1939.json).")
        else:
            determination = ("0 FDA drug-approval decision rows recorded. The official Drugs@FDA "
                             "database's earliest recorded drug-approval action is 1939-02-09 "
                             "(NDA000552), so this year has no decision record in any official "
                             "database this project can cite. Recorded as the boundary, not as "
                             "an omission.")
            basis = ("Minimum SubmissionStatusDate over the official 1938-1964 Submissions extract "
                     "is 1939-02-09; the openFDA payload block starts at decisions_1939.json.")
        register_rows.append({
            "row_id": f"PRE1939REG-{ys}",
            "year": ys,
            "era": ("Federal biologics licensure only (pre-Food-and-Drugs-Act)" if y < 1906
                    else "Pre-market approval era: 1906 Act regime (no drug approval system)" if y < 1938
                    else "Pre-market approval created: 1938 FD&C Act"),
            "agency_of_record": agency,
            "premarket_approval_regime": regime,
            "statute_citation": citation,
            "statute_enacted_date": enacted,
            "statute_verbatim_quote": quote,
            "fda_drug_approval_decisions_recorded": "0",
            "recorded_decisions_basis": basis,
            "official_fda_series_coverage": series_cov(ys),
            "landmark_event": landmark,
            "determination": determination,
            "source_url_1": u1,
            "source_url_2": u2,
            "source_url_3": u3,
            "verification_status": ("Verified - statute/regime from the cited official primary "
                                    f"source; decision count from the cited official extract ({V28})"),
            "notes": (
                "No drug-approval decision row is asserted for this year because no official "
                "record of one exists. Blank beats guessed: no drug name, sponsor, indication, "
                "ticker or count is invented to fill the year. Where a landmark event is cited "
                "it is quoted from the linked official source."
                + (" FLAGGED irregularity for review, both sides quoted from official .gov "
                   "pages: FDA's own history page (" + SRC_FDA_HISTORY + ") says 'the name of "
                   "the agency was shortened to the Food and Drug Administration in 1930', while "
                   "the USDA Food Safety and Inspection Service history page (" + SRC_USDA_FSIS +
                   ") says 'In 1931, it was renamed the Food and Drug Administration (FDA).' "
                   "FDA's page is treated as the agency of record for this register; the "
                   "conflict is reported, not resolved by choice."
                   if y in (1930, 1931) else "")
            ),
        })

    # ---- write --------------------------------------------------------------
    print("  writing tables:")
    write_csv(BOUNDARY_CSV, BOUNDARY_HEADER, boundary_rows)
    write_csv(CENSUS_CSV, CENSUS_HEADER, census_rows)
    write_csv(REGISTER_CSV, REGISTER_HEADER, register_rows)
    write_csv(STATUS_CSV, STATUS_HEADER, status_rows)

    # ---- self-checks that must hold on every run ---------------------------
    for r in register_rows:
        if r["fda_drug_approval_decisions_recorded"] != "0":
            print(f"FAIL: register row {r['row_id']} asserts a non-zero pre-1939 decision count")
            return 1
        if not (r["source_url_1"].startswith("https://") and r["source_url_2"].startswith("https://")):
            print(f"FAIL: register row {r['row_id']} lacks official source URLs")
            return 1
    banned = {"likelihood", "probability", "modelled", "ticker", "exchange", "indication"}
    for hdr in (BOUNDARY_HEADER, CENSUS_HEADER, REGISTER_HEADER, STATUS_HEADER):
        hit = {h for h in hdr if any(b in h.lower() for b in banned)}
        if hit:
            print(f"FAIL: banned column(s) {hit} in {hdr}")
            return 1
    if len(register_rows) != 37:
        print(f"FAIL: register should cover 1902-1938 (37 rows), got {len(register_rows)}")
        return 1

    print(f"\n{V28} pre-1939 boundary build complete:")
    print(f"  {len(boundary_rows)} evidence lines, {len(census_rows)} below-boundary applications, "
          f"{len(register_rows)} register years (1902-1938), {len(status_rows)} status-census rows")
    print(f"  boundary: earliest official FDA drug-approval action {earliest} (NDA{EARLIEST_APPLNO}); "
          f"0 actions in 1938; {len(low_apps)} applications below the boundary "
          f"({', '.join(low_applnos)})")
    print(f"  runner capture layer: {'joined' if census_present else 'pending'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
